### PR TITLE
Minor touch ups and refactoring

### PR DESCRIPTION
**Pull request by luispedro**
Should not have changed any functionality, but please have a look.

### CODE REVIEW

**Review by cocodyq — COMMENTED** [review]
Hi Luis,
```
def predicted_smorf_count(file_name):
    return len(_ for _ in open(file_name, 'rt'))
```
This function change meets an error:
**object of type 'generator' has no len()**

Could it be
 ```
   for count, line in enumerate(open(file_name,'r')):
        continue
    count += 1
    return count
```
Thank you!
@luispedro

**Comment by luispedro** [comment]
Thanks, that was a good catch (although the tests didn't catch it?)

I used `sum(1 for _ in open(....))` now

**Comment by celiosantosjr** [comment]
> just use it as a comprehension list
```
def predicted_smorf_count(file_name):
    return len([_ for _ in open(file_name, 'rt')])
```

**Comment by cocodyq** [comment]
> Thanks, that was a good catch (although the tests didn't catch it?)
> 
> I used `sum(1 for _ in open(....))` now

Because this is used for summary,some statistics are performed separately during the processing. I didn't add tests of summary. Maybe it should be improved.

**Pull request merged**
